name: Check Subgraph

on:
  pull_request:
    branches:
      - main

jobs:
  check-subgraphs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install wgc
        run: |
          npm install -g wgc@latest

      - name: Run GitHub
        run: |
          node ./github.js

      - name: Run subgraph checks
        run: |
          wgc -V
          wgc subgraph check employees --schema ./employees.graphqls || echo "Fail"
          wgc subgraph check family --schema ./family.graphqls  || echo "Fail"
          wgc subgraph check hobbies --schema ./hobbies.graphqls  || echo "Fail"
          wgc subgraph check products --schema ./products.graphqls  || echo "Fail"
        env:
          COSMO_API_KEY: ${{ secrets.COSMO_API_KEY }}
